# Generated by Django 5.2.4 on 2025-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="service_from_date",
            field=models.DateField(
                blank=True,
                help_text="Start date when the service was provided",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="service_to_date",
            field=models.DateField(
                blank=True,
                help_text="End date when the service was provided",
                null=True,
            ),
        ),
    ]
