# Generated by Django 5.1.7 on 2026-05-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="client_invoices/pdfs/"
            ),
        ),
    ]
