# Generated by Django 5.2.4 on 2025-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("standup", "Daily Standup"),
                            ("review", "Weekly Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
